apiVersion: v1
kind: ServiceAccount
metadata:
  name: responsible-ai-reporting-tool-sa
  namespace: irai-toolkit-test
automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: responsible-ai-admin
  namespace: irai-toolkit-test
  labels:
    app: responsible-ai-admin
spec:
  type: ClusterIP
  selector:
    app: responsible-ai-admin
  ports:
    - name: http
      port: 30016
      targetPort: 30016
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: responsible-ai-admin
  namespace: irai-toolkit-test
  labels:
    app: responsible-ai-admin
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: responsible-ai-admin
      version: v1
  template:
    metadata:
      labels:
        app: responsible-ai-admin
        version: v1
    spec:
      serviceAccountName: responsible-ai-reporting-tool-sa
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: docker-secret
      containers:
        - name: responsible-ai-admin
          image: <IMAGE_NAME>
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: admin-config
          ports:
            - containerPort: 30016
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              cpu: "1"
              memory: 3Gi
            requests:
              cpu: "250m"
              memory: 512Mi